### ISSUE TITLE
Manipulate / Bend lane form

### ISSUE THREAD

**Issue by chameleon-tbn** [kianzarrin/NodeController#3] opened 2020-05-07 13:55 UTC
While testing the Road Transition Manager (and i must say that i already love this mod!) the normal (and correct) behaviour is that the vehicles drive straight over this junctions:

![image](https://user-images.githubusercontent.com/37211016/81298363-f8067400-9074-11ea-89f6-700ed045b2ba.png)

But at a very large - very smoothed - node it would be great to have an option to manipulate the lanes in a way that they act somehowe like a road with an middle island (not really like a roundabout, as there should be no full turns possible). 

Maybe to have it easier w/o left turns:
![image](https://user-images.githubusercontent.com/37211016/81299478-92b38280-9076-11ea-82d9-68bce4db6fba.png)

Option 1 with left turns:
![image](https://user-images.githubusercontent.com/37211016/81299777-06558f80-9077-11ea-88de-b923ca765946.png)

Option 2 with left turns:
![image](https://user-images.githubusercontent.com/37211016/81299996-63e9dc00-9077-11ea-8aa0-0d83a0db20d8.png)

Why should be such an option a nice to have?

Just because of possibilities like this:
![image](https://user-images.githubusercontent.com/37211016/81301720-b3c9a280-9079-11ea-93b0-518a66e2214e.png)

or:
![image](https://user-images.githubusercontent.com/37211016/81302716-03f53480-907b-11ea-82ff-3d2db5c8bc02.png)

😄 

I don't know at all if lanes could be manipulated / bend in this way - but want just to share my thoughts :)

And maybe... some dreams come true....

**Comment by kianzarrin** [comment] 2020-05-07 15:22
this issue duplicates https://github.com/CitiesSkylinesMods/TMPE/issues/73

**Comment by kianzarrin** [comment] 2020-05-17 08:23
closing this as duplicate of TMPE issue.

**Closed as completed by kianzarrin** 2020-05-17 08:23 UTC
Labels: duplicate
